databaseChangeLog:
  - changeSet:
      id: 3.10.0
      author: GraviteeSource Team
      changes:
        - addColumn:
            tableName: ${gravitee_prefix}keys
            columns:
              - column:
                  name: days_to_expiration_on_last_notification
                  type: integer
        - addColumn:
            tableName: ${gravitee_prefix}subscriptions
            columns:
              - column:
                  name: days_to_expiration_on_last_notification
                  type: integer
        - createTable:
            tableName: ${gravitee_prefix}promotions
            columns:
              - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: api_definition, type: nclob, constraints: { nullable: false } }
              - column: {name: api_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: status, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: target_env_cockpit_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: target_env_name, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: source_env_cockpit_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: source_env_name, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
              - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }
              - column: {name: author_user_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: author_display_name, type: nvarchar(64), constraints: { nullable: true } }
              - column: {name: author_email, type: nvarchar(64), constraints: { nullable: true } }
              - column: {name: author_picture, type: nvarchar(64), constraints: { nullable: true } }
              - column: {name: author_source, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: author_source_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: target_api_id, type: nvarchar(64) }
        - addColumn:
            tableName: ${gravitee_prefix}environments
            columns:
              - column: {name: cockpit_id, type: nvarchar(64), constraints: { nullable: true } }
        - addColumn:
            tableName: ${gravitee_prefix}organizations
            columns:
              - column: {name: cockpit_id, type: nvarchar(64), constraints: { nullable: true } }