databaseChangeLog:
    - changeSet:
        id: 1.25.2
        author: GraviteeSource Team
        validCheckSum:
        - 8:67ff408ab1ca458f85386d06f45e395b
        - 8:a1872ce916e96806b18767089dde811d
        changes:
        - addColumn:
            tableName: ratelimit
            columns:
                - column:
                    name: subscription
                    type: nvarchar(64)
                - column:
                    name: limit
                    type: bigint
        - dropColumn:
            tableName: ratelimit
            columnName: last_request
        - dropColumn:
            tableName: ratelimit
            columnName: created_at
        - dropColumn:
            tableName: ratelimit
            columnName: updated_at
        - dropColumn:
            tableName: ratelimit
            columnName: async
        - addNotNullConstraint:
            columnDataType: nvarchar(64)
            columnName: subscription
            defaultNullValue: 'unknown'
            tableName: ratelimit
        - dropPrimaryKey:
            constraintName: pk_ratelimit
            tableName: ratelimit
        - modifyDataType:
            tableName: ratelimit
            columnName: key
            newDataType: nvarchar(128) not null
        - addPrimaryKey:
             constraintName: pk_ratelimit
             columnNames: key
             tableName: ratelimit
