databaseChangeLog:
    - changeSet:
        id: 1.24.0
        author: GraviteeSource Team
        changes:
        - addColumn:
            tableName: plans
            columns:
              - column:
                  name: comment_message
                  type: nvarchar(64)