databaseChangeLog:
  - changeSet:
      id: 3.11.1
      author: GraviteeSource Team
      changes:
        # dbms: mariadb, mysql
        - sql:
            dbms: mariadb, mysql
            sql: delete from `${gravitee_prefix}event_properties` where `property_key` = 'api_id';
        # dbms: postgresql, mssql
        - sql:
            dbms: postgresql, mssql
            sql: delete from ${gravitee_prefix}event_properties where property_key = 'api_id';
