databaseChangeLog:
    - changeSet:
        id: 1.25.0
        author: GraviteeSource Team
        changes:
        - createTable:
            tableName: tag_groups
            columns:
              - column: {name: tag_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: group_id, type: nvarchar(64), constraints: { nullable: false } }
        - createTable:
              tableName: application_metadata
              columns:
                  - column: {name: application_id, type: nvarchar(64), constraints: { nullable: false } }
                  - column: {name: k, type: nvarchar(128), constraints: { nullable: false } }
                  - column: {name: v, type: nvarchar(4000), constraints: { nullable: false } }

        - addPrimaryKey:
              constraintName: pk_application_metadata
              columnNames: application_id, k
              tableName: application_metadata

        - createTable:
            tableName: client_registration_providers
            columns:
              - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: name, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: description, type: nvarchar(4000), constraints: { nullable: true } }
              - column: {name: discovery_endpoint, type: nvarchar(4000), constraints: { nullable: false } }
              - column: {name: client_id, type: nvarchar(128), constraints: { nullable: false } }
              - column: {name: client_secret, type: nvarchar(128), constraints: { nullable: false } }
              - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
              - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }

        - addPrimaryKey:
            constraintName: pk_client_registration_providers
            columnNames: id
            tableName: client_registration_providers

        - createTable:
            tableName: client_registration_provider_scopes
            columns:
              - column: {name: client_registration_provider_id, type: nvarchar(64), constraints: { nullable: false } }
              - column: {name: scope, type: nvarchar(64), constraints: { nullable: false } }