databaseChangeLog:
    - changeSet:
        id: 1.25.3
        author: GraviteeSource Team
        changes:
        - addColumn:
            tableName: identity_providers
            columns:
                - column:
                    name: email_required
                    type: boolean