databaseChangeLog:
  - changeSet:
      id: 3.10.1
      author: GraviteeSource Team
      changes:
        - sql:
            dbms: mssql
            sql: update ${gravitee_prefix}parameters set value = 'themes/assets/gravitee-logo.svg' where ${gravitee_prefix}parameters.key = 'theme.logo' AND ${gravitee_prefix}parameters.value = 'themes/assets/GRAVITEE_LOGO1-01.png';
