databaseChangeLog:
  - changeSet:
      id: 3.10.1
      author: GraviteeSource Team
      changes:
        # dbms: mariadb, mysql
        - sql:
            dbms: mariadb, mysql
            sql: update `${gravitee_prefix}parameters` set value = 'themes/assets/gravitee-logo.svg' where `${gravitee_prefix}parameters.key` = 'theme.logo' AND `${gravitee_prefix}parameters.value` = 'themes/assets/GRAVITEE_LOGO1-01.png';
        # dbms: postgresql, mssql
        - sql:
            dbms: postgresql, mssql
            sql: update ${gravitee_prefix}parameters set value = 'themes/assets/gravitee-logo.svg' where ${gravitee_prefix}parameters.key = 'theme.logo' AND ${gravitee_prefix}parameters.value = 'themes/assets/GRAVITEE_LOGO1-01.png';

        # dbms: mariadb, mysql
        - sql:
            dbms: mariadb, mysql
            sql: update `${gravitee_prefix}events` SET payload=regexp_replace(payload, '"environment"', '"environmentId"') WHERE type IN ['PUBLISH_API', 'UNPUBLISH_API', 'START_API', 'STOP_API'] AND payload IS NOT NULL;
        # dbms: postgresql, mssql
        - sql:
            dbms: postgresql, mssql
            sql: update ${gravitee_prefix}events SET payload=regexp_replace(payload, '"environment"', '"environmentId"') WHERE type IN ['PUBLISH_API', 'UNPUBLISH_API', 'START_API', 'STOP_API'] AND payload IS NOT NULL;
