databaseChangeLog:
  - changeSet:
      id: 3.0.4
      author: GraviteeSource Team
      changes:
        - modifyDataType:
            tableName: subscriptions
            columnName: client_id
            newDataType: nvarchar(300)
