databaseChangeLog:
    - changeSet:
        id: 1.20.2
        author: GraviteeSource Team
        changes:
        - addColumn:
            tableName: plans
            columns:
                - column:
                    name: need_redeploy_at
                    type: timestamp(6)
