databaseChangeLog:
    - changeSet:
        id: 1.30.0
        author: GraviteeSource Team
        changes:
          - createTable:
              tableName: quality_rules
              columns:
                - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: description, type: nvarchar(256), constraints: { nullable: false } }
                - column: {name: weight, type: int, constraints: { nullable: false } }
                - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
                - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }

          - addPrimaryKey:
              constraintName: pk_quality_rules
              columnNames: id
              tableName: quality_rules

          - createTable:
              tableName: api_quality_rules
              columns:
                - column: {name: api, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: quality_rule, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: checked, type: boolean, constraints: { nullable: false } }
                - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
                - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }

          - addPrimaryKey:
              constraintName: pk_api_quality_rules
              columnNames: api, quality_rule
              tableName: api_quality_rules

          - createTable:
              tableName: dashboards
              columns:
                - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: reference_type, type: nvarchar(32), constraints: { nullable: false } }
                - column: {name: reference_id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: query_filter, type: nvarchar(128), constraints: { nullable: true } }
                - column: {name: order, type: int, constraints: { nullable: false } }
                - column: {name: enabled, type: boolean, constraints: { nullable: false } }
                - column: {name: definition, type: nclob, constraints: { nullable: true } }
                - column: {name: created_at, type: timestamp(6), constraints: { nullable: true } }
                - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }

          - addPrimaryKey:
              constraintName: pk_dashboards
              columnNames: id
              tableName: dashboards

          - createIndex:
              indexName: idx_dashboards_reference_type
              columns:
                - column:
                    name: reference_type
                    type: nvarchar(32)
              tableName: dashboards

          - addColumn:
              tableName: client_registration_providers
              columns:
                - column:
                    name: software_id
                    type: nvarchar(256)

          - dropTable:
              cascadeConstraints: true
              tableName: alerts

          - createTable:
              tableName: alert_triggers
              columns:
                - column: {name: id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: name, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: description, type: nvarchar(256), constraints: { nullable: true } }
                - column: {name: reference_type, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: reference_id, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: type, type: nvarchar(64), constraints: { nullable: false } }
                - column: {name: enabled, type: boolean, constraints: { nullable: false } }
                - column: {name: severity, type: nvarchar(64), constraints: { nullable: true } }
                - column: {name: definition, type: nclob, constraints: { nullable: false } }
                - column: {name: created_at, type: timestamp(6), constraints: { nullable: false } }
                - column: {name: updated_at, type: timestamp(6), constraints: { nullable: true } }

          - addPrimaryKey:
              constraintName: pk_alert_triggers
              columnNames: id
              tableName: alert_triggers
